export const FETCH_CONFIG_REQUEST = 'NEW_AUTH_CONTAINER_FETCH_CONFIG_REQUEST';
export const FETCH_CONFIG_SUCCESS = 'NEW_AUTH_CONTAINER_FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'NEW_AUTH_CONTAINER_FETCH_CONFIG_FAILURE';

export const CHANGE_CONFIG_MODEL = 'NEW_AUTH_CONTAINER_CHANGE_CONFIG_MODEL';
export const CHANGE_CONFIG_AUTH = 'NEW_AUTH_CONTAINER_CHANGE_CONFIG_AUTH';
export const CHANGE_CONFIG_AUTH_OAUTH = 'NEW_AUTH_CONTAINER_CHANGE_CONFIG_AUTH_OAUTH'
export const CHANGE_CONFIG_PASS = 'NEW_AUTH_CONTAINER_CHANGE_CONFIG_PASS';
export const CHANGE_CONFIG_DB = 'NEW_AUTH_CONTAINER_CHANGE_CONFIG_DB';
export const CHANGE_CONFIG_MAIL = 'NEW_AUTH_CONTAINER_CHANGE_CONFIG_MAIL';
export const SET_CONFIG_ERRORS = 'NEW_AUTH_CONTAINER_SET_CONFIG_ERRORS';

export const CHANGE_CONFIG_MODEL_LENGTH = 'NEW_AUTH_CONTAINER_CHANGE_CONFIG_MODEL_LENGTH';
export const REMOVE_CONFIG_MODEL_ROW = 'NEW_AUTH_CONTAINER_REMOVE_CONFIG_MODEL_ROW';
export const ADD_CONFIG_MODEL_ROW = 'NEW_AUTH_CONTAINER_ADD_CONFIG_MODEL_ROW';
export const CHANGE_CONFIG_MODEL_TITLE = 'NEW_AUTH_CONTAINER_CHANGE_CONFIG_MODEL_TITLE';
export const TOGGLE_CONFIG_AUTH_OAUTH = 'NEW_AUTH_CONTAINER_TOGGLE_CONFIG_AUTH_OAUTH'