export const MODEL_ADD_ROW = 'CREATE_NEW_AUTH_CONTAINER_MODEL_ADD_ROW';
export const MODEL_REMOVE_ROW = 'CREATE_NEW_AUTH_CONTAINER_MODEL_REMOVE_ROW';
export const MODEL_SET_ROW_VALUE = 'CREATE_NEW_AUTH_CONTAINER_MODEL_SET_ROW_VALUE';