export const FETCH_ALL_USERS_REQUEST = 'AUTH_CONTAINER_FETCH_ALL_USERS_REQUEST';
export const FETCH_ALL_USERS_SUCCESS = 'AUTH_CONTAINER_FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE = 'AUTH_CONTAINER_FETCH_ALL_USERS_FAILURE';