export const SET_CONTAINER = 'EDIT_AUTH_CONTAINER_SET_CONTAINER';

export const SET_NAME = 'EDIT_AUTH_CONTAINER_SET_NAME';
export const SET_TIER = 'EDIT_AUTH_CONTAINER_SET_TIER';

export const SET_CONTAINER_CONFIG_MODEL = 'EDIT_AUTH_CONTAINER_SET_CONTAINER_CONFIG_MODEL';