export const SET_CONTAINER = 'EDIT_AUTH_CONTAINER_SET_CONTAINER';

export const SET_NAME = 'EDIT_AUTH_CONTAINER_SET_NAME';
export const SET_TIER = 'EDIT_AUTH_CONTAINER_SET_TIER';

export const SET_CONTAINER_CONFIG_MODEL = 'EDIT_AUTH_CONTAINER_SET_CONTAINER_CONFIG_MODEL';
export const SET_CONTAINER_CONFIG_MODEL_LENGTH = 'EDIT_AUTH_CONTAINER_SET_CONTAINER_CONFIG_MODEL_LENGTH';
export const ADD_CONTAINER_CONFIG_MODEL_ROW = 'EDIT_AUTH_CONTAINER_ADD_CONTAINER_CONFIG_MODEL_ROW';
export const REMOVE_CONTAINER_CONFIG_MODEL_ROW = 'EDIT_AUTH_CONTAINER_REMOVE_CONTAINER_CONFIG_MODEL_ROW';

export const SET_CONTAINER_CONFIG_PASS = 'EDIT_AUTH_CONTAINER_SET_CONTAINER_CONFIG_PASS';
export const SET_CONTAINER_CONFIG_DB = 'EDIT_AUTH_CONTAINER_SET_CONTAINER_CONFIG_DB';
export const SET_CONTAINER_CONFIG_MAIL = 'EDIT_AUTH_CONTAINER_SET_CONTAINER_CONFIG_MAIL';
export const SET_CONTAINER_CONFIG_AUTH = 'EDIT_AUTH_CONTAINER_SET_CONTAINER_CONFIG_AUTH';

export const SET_CONTAINER_CONFIG_AUTH_OAUTH = 'EDIT_AUTH_CONTAINER_SET_CONTAINER_CONFIG_AUTH_OAUTH'
export const TOGGLE_CONTAINER_CONFIG_AUTH_OAUTH = 'EDIT_AUTH_CONTAINER_TOGGLE_CONTAINER_CONFIG_AUTH_OAUTH';