export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';
export const SET_ERROR_MESSAGES = 'SET_ERROR_MESSAGES';
export const SET_ERROR_OPEN = 'SET_ERROR_OPEN';