export const PUSH_ERROR = 'CREATE_NEW_AUTH_CONTAINER_PUSH_ERROR';
export const REMOVE_ERROR = 'CREATE_NEW_AUTH_CONTAINER_REMOVE_ERROR';
export const SET_ERRORS = 'CREATE_NEW_AUTH_CONTAINER_SET_ERRORS';