export const FETCH_CONTAINERS_REQUEST = 'FETCH_CONTAINER_REQUEST';
export const FETCH_CONTAINERS_SUCCESS = 'FETCH_CONTAINER_SUCCESS';
export const FETCH_CONTAINERS_FAILURE = 'FETCH_CONTAINER_FAILURE';