export const FETCH_CONTAINER_INVOICES_REQUEST = 'FETCH_CONTAINER_INVOICES_REQUEST';
export const FETCH_CONTAINER_INVOICES_SUCCESS = 'FETCH_CONTAINER_INVOICES_SUCCESS';
export const FETCH_CONTAINER_INVOICES_FAILURE = 'FETCH_CONTAINER_INVOICES_FAILURE';