export const FETCH_USER_LIST_REQUEST = 'PROJECT_PANEL_FETCH_USER_LIST_REQUEST';
export const FETCH_USER_LIST_SUCCESS = 'PROJECT_PANEL_FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_FAILURE = 'PROJECT_PANEL_FETCH_USER_LIST_FAILURE';