export const SET_PROJECT_ID = 'PROJECT_PANEL_SET_PROJECT_ID';

export const FETCH_AUTH_PROJECT_REQUEST = 'PROJECT_PANEL_FETCH_AUTH_PROJECT_REQUEST';
export const FETCH_AUTH_PROJECT_SUCCESS = 'PROJECT_PANEL_FETCH_AUTH_PROJECT_SUCCESS';
export const FETCH_AUTH_PROJECT_FAILURE = 'PROJECT_PANEL_FETCH_AUTH_PROJECT_FAILURE';