export const SET_PROJECT_ID = 'PROJECT_PANEL_SET_PROJECT_ID';
export const SET_PROJECT_SECRET = 'PROJECT_PANEL_SET_PROJECT_SECRET'

export const FETCH_AUTH_PROJECT_REQUEST = 'PROJECT_PANEL_FETCH_AUTH_PROJECT_REQUEST';
export const FETCH_AUTH_PROJECT_SUCCESS = 'PROJECT_PANEL_FETCH_AUTH_PROJECT_SUCCESS';
export const FETCH_AUTH_PROJECT_FAILURE = 'PROJECT_PANEL_FETCH_AUTH_PROJECT_FAILURE';

export const FETCH_PROJECT_DETAILS_REQUEST = 'PROJECT_PANEL_FETCH_PROJECT_DETAILS_REQUEST';
export const FETCH_PROJECT_DETAILS_SUCCESS = 'PROJECT_PANEL_FETCH_PROJECT_DETAILS_SUCCESS';
export const FETCH_PROJECT_DETAILS_FAILURE = 'PROJECT_PANEL_FETCH_PROJECT_DETAILS_FAILURE';

export const POST_AUTH_START_CONTAINER_REQUEST = 'PROJECT_PANEL_POST_AUTH_START_CONTAINER_REQUEST';
export const POST_AUTH_START_CONTAINER_SUCCESS = 'PROJECT_PANEL_POST_AUTH_START_CONTAINER_SUCCESS';
export const POST_AUTH_START_CONTAINER_FAILURE = 'PROJECT_PANEL_POST_AUTH_START_CONTAINER_FAILURE'