export const FETCH_CONFIG_REQUEST = 'EDIT_AUTH_CONTAINER_FETCH_CONFIG_REQUEST';
export const FETCH_CONFIG_SUCCESS = 'EDIT_AUTH_CONTAINER_FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'EDIT_AUTH_CONTAINER_FETCH_CONFIG_FAILURE';