export const FETCH_CONFIG_REQUEST = 'EDIT_AUTH_CONTAINER_FETCH_CONFIG_REQUEST';
export const FETCH_CONFIG_SUCCESS = 'EDIT_AUTH_CONTAINER_FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'EDIT_AUTH_CONTAINER_FETCH_CONFIG_FAILURE';

export const CHANGE_CONFIG_MODEL = 'EDIT_AUTH_CONTAINER_CHANGE_CONFIG_MODEL';
export const CHANGE_CONFIG_AUTH = 'EDIT_AUTH_CONTAINER_CHANGE_CONFIG_AUTH';
export const CHANGE_CONFIG_PASS = 'EDIT_AUTH_CONTAINER_CHANGE_CONFIG_PASS';
export const CHANGE_CONFIG_DB = 'EDIT_AUTH_CONTAINER_CHANGE_CONFIG_DB';

export const CHANGE_CONFIG_MODEL_LENGTH = 'EDIT_AUTH_CONTAINER_CHANGE_CONFIG_MODEL_LENGTH';